#!/bin/bash

function rg_color {
	CURRENT=$1 # non decimal (floored)
	TOTAL=$2 # non decimal
	HALF=$(( TOTAL / 2 )) # non decimal (floored)
	RED=255
	GREEN=255
	if [ $CURRENT -gt $HALF ]; then
		# calculate amount of red
		RED=$(( (255 / HALF) * (TOTAL - CURRENT) ))
	else
		# calculate amount of green
		GREEN=$(( (255 / HALF) * (CURRENT) ))
	fi
	RED="$(printf %02X $RED)"
	GREEN="$(printf %02X $GREEN)"
	echo "#$RED${GREEN}00"
}

INFO=$(acpi -b | head -n 1 | sed -rn 's/^.*, (.*?)%, ((.*?):[0-9]{2} )?(.*)$/\1 \3 \4/p')
BATTERY=$(echo $INFO | awk '{print $1}')
if [ "$(echo $INFO | grep charg)" == "" ]; then
	REMAIN=$(echo $INFO | awk '{print $2}')
else
	REMAIN="+"
fi

# $BATTERY
COLOR="$(rg_color $BATTERY 100)"
OUTOF20=$(( BATTERY / 5 ))
BATTERY_FILL=$(printf '▮%.0s' $(seq 1 $OUTOF20))
BATTERY_EMPTY=$(printf '▯%.0s' $(seq 1 $(( 20 - OUTOF20 ))))
BATTERY_INFO="🔋 ($REMAIN) $BATTERY_FILL$BATTERY_EMPTY"

echo -n "full_text:$BATTERY_INFO///"
echo -n "color:$COLOR///"
echo "separator_block_width:25"
