#!/bin/bash

function rg_color {
	CURRENT=$1 # non decimal (floored)
	TOTAL=$2 # non decimal
	HALF=$(( TOTAL / 2 )) # non decimal (floored)
	RED=255
	GREEN=255
	if [ $CURRENT -gt $HALF ]; then
		# calculate amount of red
		RED=$(( (255 / HALF) * (TOTAL - CURRENT) ))
	else
		# calculate amount of green
		GREEN=$(( (255 / HALF) * (CURRENT) ))
	fi
	RED="$(printf %02X $RED)"
	GREEN="$(printf %02X $GREEN)"
	echo "#$RED${GREEN}00"
}

LOCAL_IP=$(hostname -i)
COLOR="#ffff44"
VPN_COLOR="#333333"
SIGNAL_STR=$(cat /proc/net/wireless | awk 'NR==3 {print $3 00}')
SIGNAL_COLOR=$(rg_color $(printf %.f "$SIGNAL_STR") 70)
SIGNAL_INFO="📶 $SIGNAL_STR"

if [[ ! $LOCAL_IP == 127* ]]; then
	COLOR="#44ff44"
fi
if [ "$(ip addr | grep tun)" != "" ]; then
	VPN_COLOR="#aaaa00"
	VPN_STATUS=" 😎"
fi
WIRELESS_INFO="📡 $(echo $LOCAL_IP | awk '{print $NF}')$VPN_STATUS"

echo -n "full_text:$WIRELESS_INFO///"
echo -n "color:$COLOR///"
echo -n "border:$VPN_COLOR///"
echo -n "separator_block_width:10///"
echo "separator:$CONNECTED"

echo -n "full_text:$SIGNAL_INFO///"
echo -n "color:$SIGNAL_COLOR///"
echo -n "border:$VPN_COLOR///"
echo "separator_block_width:25"
